name: GraphiQL End-to-End Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
    paths:
      - '**.js'
      - '.github/workflows/*.yml'
      - '!docs/**'

jobs:
    e2e-tests:
        name: E2E tests on Node ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['18']
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Build Assets
              run: npm run build

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium firefox webkit --with-deps

            - name: Start WordPress Environment
              run: npm run wp-env -- start

            - name: Run E2E tests
              run: npm run test:e2e
              continue-on-error: true # This allows the workflow to continue even if this step fails, so that screenshots can be collected.

            - name: List Screenshots
              if: always() # Ensures this step always runs for diagnostic purposes
              run: |
                echo "Listing contents of artifacts/test-results/"
                ls -R artifacts/test-results/ || echo "No screenshots directory found"

            - name: Upload Screenshots on Failure
              if: failure() # This ensures that the following steps are only run if the previous step fails.
              uses: actions/upload-artifact@v2
              with:
                  name: failed-test-screenshots
                  path: artifacts/test-results/

            - name: Stop WordPress Environment
              run: npm run wp-env -- stop

